#!/usr/bin/env python

################################################################################
#
# Project Euler - Problem 2
#
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.
#
# Joaquin Derrac - carrdelling@gmail.com
#
################################################################################


def next_fib():
    first = 1
    second = 1

    while True:

        yield second

        next = first + second
        first = second
        second = next


if __name__ == "__main__":

    solution = 0

    for value in next_fib():

        if value > 4000000:
            break

        solution += value if value % 2 == 0 else 0

    print solution
